name: NodeJS with Grunt
on:
  push:
    branches: [ "master" ]
    paths-ignore:
      - '**/*.md' # Ignore changes to markdown files
  pull_request:
    branches: [ "master" ]
    paths-ignore:
      - '**/*.md' # Ignore changes to markdown files

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: npm install

    - name: Build and serve website
      run: grunt serve
